dist: xenial
language: python
matrix:
    include:
        - python: 3.7
          env: TOXENV=py37
        - python: 3.7
          env: TOXENV=flake8
        - python: 3.7
          env: TOXENV=codecov
install:
    - pip install tox
script:
    - tox
