language: python
python: 3.7
install:
    - pip install -r requirements.txt
matrix:
    include:
        - python: 3.7
          env=: TOXENV=flake8
    install:
        - ./.travis/install
    script:
        - ./.travis/run tox
